- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{resource_group}}"
    name: "{{storage.account}}"
    account_type: "{{storage.account_type}}"

- name: Create managed disk
  azure_rm_managed_disk:
    name: "{{disk.managed.name}}"
    location: "{{location}}"
    resource_group: "{{resource_group}}"
    disk_size_gb: "{{disk.managed.size}}"